<?php
/*
* Smart Sections Init
*
* @file           init/shortcode-mappers.php
* @package        Smart Sections
* @author         Bora Demircan & Ali Metehan Erdem
* @copyright      2018 Theme Gusta
* @license        license.txt
* @version        Release: 1.5.6
*
*/

if(!function_exists('gusta_shortcode_mappers')):
    function gusta_shortcode_mappers() {
		if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_section.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_section.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_section.php'); endif;
		if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_site_logo.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_site_logo.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_site_logo.php'); endif;
		if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_navigation.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_navigation.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_navigation.php'); endif;
		if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_section_toggle.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_section_toggle.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_section_toggle.php'); endif;
		if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_close_button.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_close_button.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_close_button.php'); endif;
		if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_search_box.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_search_box.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_search_box.php'); endif;
		if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_breadcrumb.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_breadcrumb.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_breadcrumb.php'); endif;
		if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_author_info_box.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_author_info_box.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_author_info_box.php'); endif;
		if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_social_media_links.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_social_media_links.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_social_media_links.php'); endif;
		if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_social_sharing_box.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_social_sharing_box.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_social_sharing_box.php'); endif;
		if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_post_listing.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_post_listing.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_post_listing.php'); endif;
		if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_post_filter.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_post_filter.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_post_filter.php'); endif;
		if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_taxonomy_listing.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_taxonomy_listing.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_taxonomy_listing.php'); endif;
		if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_post_carousel.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_post_carousel.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_post_carousel.php'); endif;
		if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_post_title.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_post_title.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_post_title.php'); endif;
		if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_post_content.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_post_content.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_post_content.php'); endif;
		if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_post_excerpt.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_post_excerpt.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_post_excerpt.php'); endif;
		if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_post_featured_image.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_post_featured_image.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_post_featured_image.php'); endif;
		if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_post_featured_image_as_background.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_post_featured_image_as_background.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_post_featured_image_as_background.php'); endif;
		if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_post_date.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_post_date.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_post_date.php'); endif;
		if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_post_author.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_post_author.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_post_author.php'); endif;
		if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_post_author_image.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_post_author_image.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_post_author_image.php'); endif;
		if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_post_categories.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_post_categories.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_post_categories.php'); endif;
		if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_post_tags.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_post_tags.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_post_tags.php'); endif;
		if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_post_taxonomies.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_post_taxonomies.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_post_taxonomies.php'); endif;
		if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_post_read_more_button.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_post_read_more_button.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_post_read_more_button.php'); endif;
		if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_post_custom_field.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_post_custom_field.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_post_custom_field.php'); endif;
		if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_text.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_text.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_text.php'); endif;
		if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_container.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_container.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_container.php'); endif;
		if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_facebook_comment_box.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_facebook_comment_box.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_facebook_comment_box.php'); endif;
		if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_disqus_comment_box.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_disqus_comment_box.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_disqus_comment_box.php'); endif;
  	  if ( in_array( 'woocommerce/woocommerce.php', apply_filters( 'active_plugins', get_option( 'active_plugins' ) ) ) ) {
		  if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_cart_icon.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_cart_icon.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_cart_icon.php'); endif;
		  if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_add_to_cart.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_add_to_cart.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_add_to_cart.php'); endif;
		  if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_product_price.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_product_price.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_product_price.php'); endif;
		  if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_wc_product_title.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_wc_product_title.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_wc_product_title.php'); endif;
		  if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_wc_product_images.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_wc_product_images.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_wc_product_images.php'); endif;
		  //include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_wc_product_meta.php' );
		  if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_wc_product_rating.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_wc_product_rating.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_wc_product_rating.php'); endif;
		  if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_wc_product_sale_label.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_wc_product_sale_label.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_wc_product_sale_label.php'); endif;
		  if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_wc_product_featured_label.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_wc_product_featured_label.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_wc_product_featured_label.php'); endif;
		  if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_wc_product_description.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_wc_product_description.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_wc_product_description.php'); endif;
		  if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_wc_product_short_description.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_wc_product_short_description.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_wc_product_short_description.php'); endif;
		  if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_wc_product_sku.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_wc_product_sku.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_wc_product_sku.php'); endif;
		  if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_wc_product_categories.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_wc_product_categories.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_wc_product_categories.php'); endif;
		  if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_wc_product_tags.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_wc_product_tags.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_wc_product_tags.php'); endif;
		  if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_wc_direct_checkout.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_wc_direct_checkout.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_wc_direct_checkout.php'); endif;
		  if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_wc_product_additional_information.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_wc_product_additional_information.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_wc_product_additional_information.php'); endif;
		  if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_wc_product_reviews.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_wc_product_reviews.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_wc_product_reviews.php'); endif;
		  if (file_exists(get_theme_file_path().'/smart-sections/vc_elements/gusta_wc_product_upsells.php')): include( get_theme_file_path().'/smart-sections/vc_elements/gusta_wc_product_upsells.php'); else: include( SMART_SECTIONS_PLUGIN_PATH . 'vc_elements/gusta_wc_product_upsells.php'); endif;
  	  }
      
    }
    add_action( 'init', 'gusta_shortcode_mappers', 999999999 );
  endif;